### ISSUE TITLE
Not Working in ie11

### ISSUE THREAD

**Issue by emekanw** [CharlesMangwa/react-data-fetching#30] opened 2018-09-17 20:17 UTC
https://github.com/CharlesMangwa/react-data-fetching/blob/35b8449cfb205810b756ebde61d7fb3fd50e5f49/modules/requestToApi.js#L126

**Comment by CharlesMangwa** [comment] 2018-09-27 12:41
Duplicate of #18, feel free to continue commenting there :)

**Closed** 2018-09-27 13:27 UTC
Labels: bug 🙃
